#!/bin/sh

# For testing the development version. Uses current
# opam prefix and a cache in /tmp/odig-cache.

P=$(opam var prefix)

export ODIG_CACHE_DIR=/tmp/odig-cache
export ODIG_LIB_DIR=$P/lib
export ODIG_DOC_DIR=$P/doc
export ODIG_SHARE_DIR=$P/share
export ODIG_ODOC_TRACE=/tmp/odig-cache/trace.json
export ODIG_VERBOSITY=info
