#!/bin/sh

# To run and test the odig built from the repo as if was in your PATH
# issue:
#
#  source dev-env
#
# odigs current opam prefix and uses a cache in /tmp/odig-cache.

P=$(opam var prefix)
export ODIG_CACHE_DIR=/tmp/odig-cache
export ODIG_LIB_DIR=$P/lib
export ODIG_DOC_DIR=$P/doc
export ODIG_SHARE_DIR=$P/share

ODIG_BRZO=$(brzo --path)
ODIG_OCB=$(pwd)/_build/src/brzo_bin.native

odig ()
{
  if [ -e $ODIG_BRZO ]; then
     $ODIG_BRZO $@
  elif [ -e $ODIG_OCB ]; then
     $ODIG_OCB $@
  else
    echo "No dev build found"
  fi
}
