(*---------------------------------------------------------------------------
   Copyright (c) 2018 The odig programmers. All rights reserved.
   Distributed under the ISC license, see terms at the end of the file.
   %%NAME%% %%VERSION%%
  ---------------------------------------------------------------------------*)

(** mld and HTML pages generated by odig itself. *)

open Odig_support

(** {1:pages Pages} *)

val index_mld :
  Conf.t -> Pkg.t -> Pkg_info.t -> user_index:string option -> string
(** [index_mld conf pkg pkg_info ~index] is an [index.mld] page for
    package [pkg] with info [pkg_info]. If [user_index] is [Some
    content] that user provided content is integrated in the result (a
    leading section ["{0"] is stripped off though) and no module index
    is generated by the function. *)

val pkg_list :
  Conf.t -> index_title:string option -> raw_index_intro:string option -> string
(** [pkg_list c ~index_title ~raw_index_intro] is an HTML page for the
    packages that have their documentation generated in
    [c]. [index_title] is a title for the page with the list of
    packages; if unspecified one is automatically generated.
    [raw_index_intro] is the HTML markup that is inserted before the
    list of packages; if unspecified one is automatically
    generated. *)

(*---------------------------------------------------------------------------
   Copyright (c) 2018 The odig programmers

   Permission to use, copy, modify, and/or distribute this software for any
   purpose with or without fee is hereby granted, provided that the above
   copyright notice and this permission notice appear in all copies.

   THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
   WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
   MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
   ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
   WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
   ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
   OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
  ---------------------------------------------------------------------------*)
